server:
  port: 80

spring:
  application:
    name: cloud-order
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    # 表示是否将自己注册进EurkaServer 默认是true
    register-with-eureka