server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment_route01 # 唯一ID
        uri: lb://CLOUD-PAYMENT-SERVICE # 匹配后提供服务的地址
        predicates:
          - Path=/payment/get/**  # 断言 路径相匹配的进行路由

      - id: payment_route02
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/lb/**

#        - Query=username, \d+  # 参数 username必须是整数
#        - Method=GET # 请求方法必须是get请求
#        - Header=X-Request-Id, \d+   # 请求头必须是 X-Request-Id:整数
#        - Before=2021-04-03T14:55:00.474+08:00[Asia/Shanghai]
#        - Cookie=username, aa  # cookie
#        - After=2020-04-03T14:49:00.474+08:00[Asia/Shanghai]
#        - Between=2020-04-03T14:49:00.474+08:00[Asia/Shanghai], 2020-04-03T15:49:00.474+08:00[Asia/Shanghai]
        filters:
        - AddResponseHeader=X-Response-Red, Blue
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由


eureka:
  client:
    # 表示是否将自己注册进EurkaServer 默认是true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认是true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-gateway-service